apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authentication-db
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: authentication-db
    spec:
      containers:
        - name: authentication-db
          image: postgres:latest 
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: authentication-db-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: authentication-db
      volumes:
        - name: authentication-db
          persistentVolumeClaim:
            claimName: authentication-pv-claim
