kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: authentication-pv-claim
  labels:
    app: authentication-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
